#该配置文件中请勿使用tab键
permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet #markdown 解释器

# 作者信息
author: 
  name:  
  email: liuwenyu21@gmail.com
  link: http://liuwenyu.com
  github: http://github.com/liuwenyu

# 站点信息
title: 落枫的博客 
description: 落枫的博客
url: http://liuwenyu.com
#rss_url: /pages/atom.xml
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.png
favicon: /public/upload/gavatar/favicon.ico
#weixin:  /public/upload/weixin/weixin.png

# google analytics 设置
#ga:
# id: UA-43667383-1
# url: liuwenyu.com

# disqus 设置
disqus:
  shortname: liuwenyu

# 主题设置，自动激活某个标签
active: 技术学习

# 首页除了最新文章外显示分类
cates: 
  #- OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
